spring.application.name=Student
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/std
spring.datasource.username=root
spring.datasource.password=Sows@2005
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
